[package]
name = "webauthn_verifier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getrandom = { version = "0.2.15", features = ["js"] }
p256 = { version = "0.13.2", features = ["ecdsa", "pem", "arithmetic", "jwk"] }
sha2 = "0.10.2"
coset = "0.3.8"
hex = "0.4.3"
rand = "0.8.5"
ciborium = "0.2.2"
passkey = "0.3.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.15", features = ["js"] }
